# DEPRECATED: Use polarization_full.py instead.
# This file is kept for backward compatibility only.
import warnings as _warnings
_warnings.warn(
    "mlx_class.polarization is deprecated. Use mlx_class.polarization_full instead.",
    DeprecationWarning,
    stacklevel=2,
)

"""
polarization.py — CMB E-mode polarization power spectrum (basic).

CMB polarization is generated by the photon quadrupole Theta_2 at recombination.
The polarization source function is:

  S_E(k, tau) = g(tau) * sqrt(6)/10 * Theta_2(k, tau)

For the instantaneous recombination approximation:
  C_l^EE = (4 pi) int dk/k P_R(k) * |Delta_l^E(k)|^2

where Delta_l^E uses the E-mode transfer function with spin-2 projection:
  Delta_l^E(k) = sqrt(6)/10 * Theta_2(k, tau_rec) * epsilon_l(x)

with x = k * D_A, and:
  epsilon_l(x) = sqrt((l+2)!/(l-2)!) / x^2 * j_l(x)

For l >> 1, epsilon_l(x) ~ (l^2/x^2) * j_l(x).

TIGHT-COUPLING APPROXIMATION for Theta_2:
  When |kappa_dot| >> k (tight coupling), the quadrupole is suppressed:
    Theta_2 ~ (8/15) * (k / |kappa_dot|) * Theta_1

  This comes from the Boltzmann hierarchy:
    0 = k/5 * (2 Theta_1 - 3 Theta_3) - (9/10) * |kappa_dot| * Theta_2
  and Theta_3 << Theta_1, giving:
    Theta_2 = (2k)/(5 * (9/10) * |kappa_dot|) * Theta_1
            = (4/9) * k * Theta_1 / |kappa_dot|

  But more precisely, the polarization-generating quadrupole in the
  full treatment has a factor of (8/15) from the angular integration
  of Thomson scattering.

IMPLEMENTATION:
  1. If HiRes solver result is available (has Theta_2 from the hierarchy):
     use Theta_2 directly.
  2. Otherwise, estimate Theta_2 from the tight-coupling formula:
     Theta_2 ~ (4/9) * k * Theta_1 / |kappa_dot(tau_rec)|
  This gives the correct SHAPE but approximate AMPLITUDE.

Author: Sheng-Kai Huang, 2026
"""
import numpy as np
import mlx.core as mx
from scipy.special import spherical_jn, factorial
from scipy.interpolate import interp1d
import time

from .background import A_s, n_s, k_pivot, T_CMB


# ============================================================================
# E-mode angular projection factor: epsilon_l(x) = sqrt((l+2)!/(l-2)!) / x^2 * j_l(x)
# ============================================================================

def _epsilon_l(ell, x_arr):
    """
    Spin-2 Bessel projection factor for E-mode polarization.

    epsilon_l(x) = sqrt((l+2)!/(l-2)!)) / x^2 * j_l(x)

    For l >= 2:
      sqrt((l+2)!/(l-2)!) = sqrt((l-1)*l*(l+1)*(l+2))

    Handles x=0 gracefully (epsilon_l -> 0).
    """
    l = int(ell)
    if l < 2:
        return np.zeros_like(x_arr)

    # Prefactor: sqrt((l+2)!/(l-2)!) = sqrt((l-1)*l*(l+1)*(l+2))
    prefactor = np.sqrt(float((l - 1) * l * (l + 1) * (l + 2)))

    jl = spherical_jn(l, x_arr)

    # Avoid division by zero: for x << 1, epsilon_l ~ 0 anyway
    x_safe = np.where(np.abs(x_arr) < 1e-10, 1e-10, x_arr)
    result = prefactor * jl / (x_safe ** 2)

    # Zero out truly small x
    result = np.where(np.abs(x_arr) < 1e-10, 0.0, result)
    return result


# ============================================================================
# Extract Theta_2 from solver result
# ============================================================================

def _get_theta2_from_result(result, solver_type):
    """
    Extract Theta_2(k, tau_rec) from a solver result.

    For 'hires': Theta_2 is solved directly in the photon hierarchy.
    For others: estimate from tight-coupling formula.
    """
    bg = result.bg

    if solver_type == 'hires':
        # HiRes solver has Theta_2 directly
        Theta_0, Phi, Psi, v_b, Theta_2 = result.source_at_recombination()
        k_arr = result.k_arr
        return k_arr, Theta_2, True

    # For TCA-based solvers: estimate Theta_2 from the tight-coupling formula
    # Theta_2 ~ (4/9) * k * Theta_1 / |kappa_dot(tau_rec)|
    k_arr = result.k_arr
    y_np = np.array(result.y if hasattr(result, 'y') else result.y_tca)

    if solver_type == 'neutrino':
        from .perturbations_neutrino import IDX_THETA_1
        Theta_1 = y_np[:, IDX_THETA_1]
    elif solver_type == 'implicit':
        from .perturbations_implicit import TCA_THETA_1
        Theta_1 = y_np[:, TCA_THETA_1]
    elif solver_type == 'explicit':
        from .perturbations import TCA_THETA_1
        Theta_1 = y_np[:, TCA_THETA_1]
    else:
        raise ValueError(f"Unknown solver_type: {solver_type}")

    # kappa_dot at tau_rec
    kappa_dot_rec = bg.kappa_dot_at_tau(np.array([bg.tau_rec]))[0]
    abs_kappa_dot = np.abs(kappa_dot_rec)

    # Tight-coupling estimate for Theta_2
    # Theta_2 = (4/9) * k * Theta_1 / |kappa_dot|
    if abs_kappa_dot > 1e-10:
        Theta_2 = (4.0 / 9.0) * k_arr * Theta_1 / abs_kappa_dot
    else:
        # kappa_dot ~ 0 means fully decoupled; Theta_2 is large
        # Use the free-streaming limit: Theta_2 ~ 0.1 * Theta_0
        from .perturbations_implicit import TCA_THETA_0
        Theta_0 = y_np[:, TCA_THETA_0]
        Theta_2 = 0.1 * Theta_0

    # Apply Silk damping
    silk = np.exp(-(k_arr / bg.k_D) ** 2)
    Theta_2 = Theta_2 * silk

    return k_arr, Theta_2, False


# ============================================================================
# E-mode C_l^EE computation
# ============================================================================

def compute_cl_ee(result, ell_values, solver_type='implicit'):
    """
    Compute the E-mode polarization power spectrum C_l^EE.

    C_l^EE = (4 pi) int dk/k P_R(k) * |Delta_l^E(k)|^2

    where Delta_l^E(k) = (sqrt(6)/10) * Theta_2(k) * epsilon_l(k*D_A)

    Parameters
    ----------
    result : solver result
        Output from any Boltzmann solver.
    ell_values : array
        Multipole values (must be >= 2).
    solver_type : str
        'implicit', 'neutrino', 'hires', 'explicit'

    Returns
    -------
    ell_values : array
    Cl_EE : array
        C_l^EE (dimensionless).
    Dl_EE : array
        l(l+1) C_l^EE / (2 pi) in muK^2.
    """
    t0 = time.time()

    bg = result.bg
    D_A = bg.D_A

    # Get Theta_2
    k_arr, Theta_2, is_exact = _get_theta2_from_result(result, solver_type)
    source_label = "exact (hierarchy)" if is_exact else "estimated (TCA)"
    print(f"[EE] Theta_2 source: {source_label}")
    print(f"[EE] Theta_2 range: [{np.min(Theta_2):.4e}, {np.max(Theta_2):.4e}]")

    # Polarization source: S_E = sqrt(6)/10 * Theta_2
    S_E = np.sqrt(6.0) / 10.0 * Theta_2

    # Filter to ell >= 2 only
    ell_values = np.asarray(ell_values, dtype=int)
    ell_values = ell_values[ell_values >= 2]
    N_ell = len(ell_values)
    N_k = len(k_arr)

    # Bessel arguments
    x_arr = k_arr * D_A

    # Primordial power spectrum
    P_R = A_s * (k_arr / k_pivot) ** (n_s - 1.0)

    # Compute epsilon_l table
    print(f"[EE] Computing epsilon_l for {N_ell} ells...")
    t_bessel = time.time()
    eps_table = np.zeros((N_ell, N_k), dtype=np.float32)
    for il, ell in enumerate(ell_values):
        eps_table[il] = _epsilon_l(ell, x_arr)
    print(f"[EE] Bessel: {time.time() - t_bessel:.2f}s")

    # Transfer function: Delta_l^E(k) = S_E(k) * epsilon_l(k * D_A)
    Delta_l_E = S_E[None, :] * eps_table  # (N_ell, N_k)

    # C_l = 4 pi int dk/k P_R |Delta_l|^2
    integrand = (P_R[None, :] * Delta_l_E ** 2).astype(np.float32)
    lnk = np.log(k_arr)
    dlnk = np.diff(lnk).astype(np.float32)

    # GPU integration
    integrand_gpu = mx.array(integrand)
    dlnk_gpu = mx.array(dlnk)
    mid = 0.5 * (integrand_gpu[:, :-1] + integrand_gpu[:, 1:])
    Cl_gpu = 4.0 * np.pi * mx.sum(mid * dlnk_gpu[None, :], axis=1)
    mx.eval(Cl_gpu)

    Cl_EE = np.maximum(np.array(Cl_gpu), 0.0)

    # D_l in muK^2
    ell_f = ell_values.astype(float)
    Dl_EE = ell_f * (ell_f + 1.0) * Cl_EE / (2.0 * np.pi) * (T_CMB * 1e6) ** 2

    t_total = time.time() - t0
    print(f"[EE] C_l^EE computed in {t_total:.2f}s")
    print(f"[EE] D_l^EE range: [{np.min(Dl_EE):.2e}, {np.max(Dl_EE):.2e}] uK^2")

    return ell_values, Cl_EE, Dl_EE


# ============================================================================
# Plotting
# ============================================================================

def plot_cl_ee(ell_values, Dl_EE, out_path=None, Dl_TT=None,
               ell_TT=None, ell_max=2500):
    """
    Generate E-mode polarization power spectrum plot.

    Parameters
    ----------
    ell_values : array
        Multipole values.
    Dl_EE : array
        D_l^EE in muK^2.
    out_path : str or None
        Save path.
    Dl_TT : array or None
        TT spectrum for comparison (same ell grid or separate).
    ell_TT : array or None
        ell values for TT (if different from EE).
    ell_max : int
        Maximum ell for plot.
    """
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import os

    if Dl_TT is not None:
        fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    else:
        fig, axes = plt.subplots(1, 1, figsize=(8, 6))
        axes = [axes]

    # EE spectrum
    ax = axes[0]
    mask = ell_values <= ell_max
    ax.semilogy(ell_values[mask], Dl_EE[mask], 'r-', lw=1.5,
                label=r'$D_\ell^{EE}$ (mlx\_class)')
    ax.set_xlabel('Multipole l', fontsize=13)
    ax.set_ylabel(r'$D_\ell^{EE}$ [$\mu K^2$]', fontsize=13)
    ax.set_title('CMB E-mode Polarization', fontsize=14)
    ax.legend(fontsize=11)
    ax.set_xlim(2, ell_max)

    # Peak finding
    from scipy.signal import find_peaks
    from scipy.interpolate import interp1d as interp

    l_full = np.arange(2, min(ell_max + 1, int(ell_values[mask][-1]) + 1))
    if len(ell_values[mask]) > 10:
        f = interp(ell_values[mask], Dl_EE[mask], kind='cubic',
                   fill_value='extrapolate')
        Dl_full = np.maximum(f(l_full), 0.0)
        peaks, _ = find_peaks(Dl_full, distance=60, prominence=0.1 * np.max(Dl_full))
        if len(peaks) > 0:
            colors = ['blue', 'green', 'orange', 'purple', 'brown']
            for i, p in enumerate(peaks[:5]):
                ax.plot(l_full[p], Dl_full[p], 'o', color=colors[i % 5], ms=8)
                ax.annotate(f'l={l_full[p]}',
                            (l_full[p], Dl_full[p] * 1.3),
                            fontsize=9, ha='center', color=colors[i % 5])

    # TT comparison
    if Dl_TT is not None and len(axes) > 1:
        ax2 = axes[1]
        if ell_TT is None:
            ell_TT = ell_values
        mask_TT = ell_TT <= ell_max
        ax2.plot(ell_TT[mask_TT], Dl_TT[mask_TT], 'b-', lw=1.2,
                 label=r'$D_\ell^{TT}$')
        ax2.plot(ell_values[mask], Dl_EE[mask], 'r-', lw=1.2,
                 label=r'$D_\ell^{EE}$')
        ax2.set_xlabel('Multipole l', fontsize=13)
        ax2.set_ylabel(r'$D_\ell$ [$\mu K^2$]', fontsize=13)
        ax2.set_title('TT vs EE Comparison', fontsize=14)
        ax2.set_yscale('log')
        ax2.legend(fontsize=11)
        ax2.set_xlim(2, ell_max)

    plt.tight_layout()

    if out_path is None:
        out_dir = os.path.dirname(os.path.abspath(__file__))
        out_path = os.path.join(out_dir, 'cl_ee_polarization.png')

    plt.savefig(out_path, dpi=150)
    plt.close()
    print(f"[EE] Plot saved: {out_path}")

    return out_path


# ============================================================================
# Self-test
# ============================================================================

def _test_polarization():
    """
    Test the E-mode polarization computation.
    1. Verify epsilon_l normalization
    2. Compute C_l^EE
    3. Check peak structure (EE peaks between TT peaks)
    """
    print("=" * 70)
    print("TEST: CMB E-mode Polarization C_l^EE")
    print("=" * 70)

    from .background import Background

    # Background
    bg = Background(khronon=False)
    bg.solve()

    # k-grid
    k_arr = np.geomspace(5e-4, 0.35, 500).astype(np.float32)

    # Solve with implicit solver
    from .perturbations_implicit import ImplicitBoltzmannSolver
    solver = ImplicitBoltzmannSolver(bg, k_arr)
    result = solver.solve()

    # Test 1: epsilon_l
    print("\n--- Test 1: epsilon_l projection ---")
    x_test = np.linspace(0.1, 100, 1000)
    eps2 = _epsilon_l(2, x_test)
    eps10 = _epsilon_l(10, x_test)
    eps100 = _epsilon_l(100, x_test)
    print(f"  epsilon_2 max: {np.max(np.abs(eps2)):.4f}")
    print(f"  epsilon_10 max: {np.max(np.abs(eps10)):.4f}")
    print(f"  epsilon_100 max: {np.max(np.abs(eps100)):.4f}")
    if np.all(np.isfinite(eps2)) and np.all(np.isfinite(eps100)):
        print("  PASS: All finite")
    else:
        print("  FAIL: Non-finite values")

    # Test 2: C_l^EE
    print("\n--- Test 2: C_l^EE computation ---")
    ell_values = np.unique(np.concatenate([
        np.arange(2, 30, 1), np.arange(30, 100, 2),
        np.arange(100, 500, 4), np.arange(500, 1500, 8),
        np.arange(1500, 2501, 12),
    ])).astype(int)

    ell_ee, Cl_EE, Dl_EE = compute_cl_ee(result, ell_values, solver_type='implicit')
    print(f"  D_l^EE range: [{np.min(Dl_EE):.4f}, {np.max(Dl_EE):.4f}] uK^2")

    # Test 3: Peak structure
    print("\n--- Test 3: EE peak structure ---")
    from scipy.signal import find_peaks
    from scipy.interpolate import interp1d

    l_full = np.arange(2, 2501)
    f = interp1d(ell_ee, Dl_EE, kind='cubic', fill_value='extrapolate')
    Dl_full = np.maximum(f(l_full), 0.0)
    peaks, _ = find_peaks(Dl_full, distance=60, prominence=0.1 * np.max(Dl_full))
    if len(peaks) > 0:
        peak_ls = l_full[peaks[:5]]
        peak_Ds = Dl_full[peaks[:5]]
        print(f"  EE peaks at l = {peak_ls}")
        print(f"  Heights = {[f'{d:.2f}' for d in peak_Ds]} uK^2")
        # EE peaks should be approximately between TT peaks
        # First EE peak ~ 140 (between l=0 and l=220 TT peaks)
        # Second EE peak ~ 400 (between TT peaks at 220 and 540)
    else:
        print("  WARNING: No peaks found")

    # Test 4: Stability
    print("\n--- Test 4: Stability ---")
    has_nan = np.any(np.isnan(Dl_EE))
    has_inf = np.any(np.isinf(Dl_EE))
    has_neg = np.any(Dl_EE < 0)
    print(f"  NaN: {has_nan}, Inf: {has_inf}, Negative: {has_neg}")
    if not (has_nan or has_inf):
        print("  PASS: All finite")
    else:
        print("  FAIL!")

    # Plot
    print("\n--- Generating plot ---")
    # Also compute TT for comparison
    from .spectra import compute_cl
    Theta_0, Phi, v_b = result.source_at_recombination()
    source_SW = Theta_0 + Phi
    _, _, Dl_TT = compute_cl(source_SW, k_arr, ell_values, bg.D_A)

    plot_cl_ee(ell_ee, Dl_EE, Dl_TT=Dl_TT, ell_TT=ell_values)

    print("\n" + "=" * 70)
    print("E-MODE POLARIZATION TEST COMPLETE")
    print("=" * 70)

    return ell_ee, Dl_EE


if __name__ == '__main__':
    _test_polarization()
